### ISSUE TITLE
Issues with CSS files

### ISSUE THREAD

**Issue by ipv6freely** [eseca/custom-gamepadviewer-skins#1]
ibuffalo-map-skin.css seems to work great for everything except D-Pad, which doesn't appear at all for me. The normal skin.css works for D-Pad but nothing else.

I tried to fork the repo and make some modifications, but for some reason gamepadviewer.com doesn't seem to like my CSS? I don't understand why. No controller shows up in OBS at all if I use my forked version of the css file. 

https://raw.githubusercontent.com/ipv6freely/custom-gamepadviewer-skins/master/snes/ibuffalo-map-skin.css

I don't understand why it matters where the CSS file is actually located. 

I'm 100% on board with spending the time to modify the CSS files myself and submitting a pull request, but I have no way to test them.

**Comment by eseca** [comment]
It's been a while since I used this. But I can test it myself as I still have the ibuffalo controller if that helps.

**Comment by ipv6freely** [comment]
To be honest I actually grabbed it and re-wrote it specifically for SNES. It seemed to not work with the D-Pad so I made that work too.

https://github.com/ipv6freely/snes-skin-for-gamepadviewer
